#include "dse/query/cache.hpp"
#include <functional>
namespace dse::query {namespace {void combine(std::size_t& seed,std::size_t value){seed^=value+0x9e3779b97f4a7c15ULL+(seed<<6U)+(seed>>2U);}}
std::size_t QueryResultCache::Hash::operator()(const QueryCacheKey& key)const noexcept{std::size_t seed=std::hash<std::uint64_t>{}(key.generation.value());combine(seed,std::hash<std::string>{}(key.schema_fingerprint));combine(seed,std::hash<std::string>{}(key.plan));combine(seed,std::hash<std::size_t>{}(key.top_k));combine(seed,std::hash<std::string>{}(key.scoring_fingerprint));return seed;}
std::size_t QueryResultCache::measure(const QueryCacheKey& key,const SearchResult& result)noexcept{std::size_t bytes=sizeof(Entry)+key.schema_fingerprint.size()+key.plan.size()+key.scoring_fingerprint.size();for(const auto& hit:result.hits)bytes+=sizeof(SearchHit)+hit.document_id.value().size();return bytes;}
std::optional<SearchResult> QueryResultCache::get(const QueryCacheKey& key){std::lock_guard lock(mutex_);const auto found=lookup_.find(key);if(found==lookup_.end()){++misses_;return std::nullopt;}++hits_;entries_.splice(entries_.begin(),entries_,found->second);return found->second->result;}
void QueryResultCache::put(QueryCacheKey key,SearchResult result){std::lock_guard lock(mutex_);if(const auto found=lookup_.find(key);found!=lookup_.end()){bytes_-=found->second->bytes;entries_.erase(found->second);lookup_.erase(found);}const auto bytes=measure(key,result);if(bytes>maximum_bytes_)return;entries_.push_front({std::move(key),std::move(result),bytes});lookup_[entries_.front().key]=entries_.begin();bytes_+=bytes;while(bytes_>maximum_bytes_&&!entries_.empty()){auto last=std::prev(entries_.end());bytes_-=last->bytes;lookup_.erase(last->key);entries_.erase(last);++evictions_;}}
void QueryResultCache::invalidate_before(GenerationId generation){std::lock_guard lock(mutex_);for(auto it=entries_.begin();it!=entries_.end();){if(it->key.generation<generation){bytes_-=it->bytes;lookup_.erase(it->key);it=entries_.erase(it);}else ++it;}}
QueryCacheStatistics QueryResultCache::statistics()const{std::lock_guard lock(mutex_);return {entries_.size(),bytes_,hits_,misses_,evictions_};}
}  // namespace dse::query
