#include "dse/distributed/local_cluster.hpp"
#include "dse/ranking/top_k.hpp"
#include <future>
#include <limits>
#include <map>
#include <utility>
namespace dse::distributed {namespace {
ClusterError fail(ClusterErrorCode code,std::string message){return {code,std::move(message)};}
class ShardSearchView final:public index::SearchIndexView{
 public:ShardSearchView(const index::SearchIndexView& local,const index::SearchIndexView& global):local_(local),global_(global){}
 const index::TermEntry* lookup(std::string_view field,std::string_view term)const override{const auto* local=local_.lookup(field,term);if(local==nullptr)return nullptr;auto key=std::pair<std::string,std::string>{std::string(field),std::string(term)};auto [it,inserted]=terms_.try_emplace(std::move(key),*local);if(inserted){const auto* global=global_.lookup(field,term);it->second.document_frequency=global==nullptr?0U:global->document_frequency;}return &it->second;}
 const index::DocumentRecord* document(const DocumentId& id)const override{return local_.document(id);}const index::DocumentRecord* document(InternalDocumentId id)const override{return local_.document(id);}std::optional<InternalDocumentId> internal_id(const DocumentId& id)const noexcept override{return local_.internal_id(id);}const DocumentId* external_id(InternalDocumentId id)const noexcept override{return local_.external_id(id);}std::vector<InternalDocumentId> live_document_ids()const override{return local_.live_document_ids();}std::size_t live_document_count()const noexcept override{return global_.live_document_count();}index::FieldStatistics field_statistics(std::string_view field)const noexcept override{return global_.field_statistics(field);}const index::IndexSchema& schema()const noexcept override{return global_.schema();}bool validate_invariants(std::string* reason=nullptr)const override{return local_.validate_invariants(reason);}
 private:const index::SearchIndexView& local_;const index::SearchIndexView& global_;mutable std::map<std::pair<std::string,std::string>,index::TermEntry> terms_;
};}
std::size_t StableShardRouter::route(const DocumentId& id)const noexcept{std::uint64_t hash=14695981039346656037ULL;for(const char character:id.value()){const auto byte=static_cast<unsigned char>(character);hash^=byte;hash*=1099511628211ULL;}return shard_count_==0U?0U:static_cast<std::size_t>(hash%shard_count_);}
LocalShardCluster::LocalShardCluster(std::size_t count,index::IndexSchema schema):router_(count),global_(schema){shards_.reserve(count);for(std::size_t i=0;i<count;++i)shards_.push_back(std::make_unique<index::InMemoryIndex>(schema));}
std::expected<std::unique_ptr<LocalShardCluster>,ClusterError> LocalShardCluster::create(std::size_t shard_count,index::IndexSchema schema){if(shard_count==0U||shard_count>1024U)return std::unexpected(fail(ClusterErrorCode::invalid_shard_count,"shard count must be between 1 and 1024"));return std::unique_ptr<LocalShardCluster>(new LocalShardCluster(shard_count,std::move(schema)));}
std::expected<void,ClusterError> LocalShardCluster::put(Document document){std::unique_lock lock(mutex_);const auto shard=router_.route(document.id);Document copy=document;auto global=global_.put(std::move(document));if(!global)return std::unexpected(fail(ClusterErrorCode::mutation_error,global.error().message));auto local=shards_[shard]->put(std::move(copy));if(!local)return std::unexpected(fail(ClusterErrorCode::mutation_error,local.error().message));return{};}
std::expected<void,ClusterError> LocalShardCluster::erase(const DocumentId& id,std::uint64_t version){return put({.id=id,.fields={},.stored_metadata={},.version=version,.deleted=true});}
std::expected<query::SearchResult,ClusterError> LocalShardCluster::search(const query::QueryNode& query,const query::SearchOptions& options)const{std::shared_lock lock(mutex_);std::vector<std::future<std::expected<query::SearchResult,query::ExecutionError>>> futures;futures.reserve(shards_.size());for(const auto& shard:shards_)futures.push_back(std::async(std::launch::async,[&,local=shard.get()]{ShardSearchView view(*local,global_);return query::QueryExecutor(view).search(query,options);}));ranking::TopKCollector collector(options.top_k);std::size_t total{};for(auto& future:futures){auto result=future.get();if(!result)return std::unexpected(fail(ClusterErrorCode::execution_error,result.error().message));if(result->total_hits>std::numeric_limits<std::size_t>::max()-total)return std::unexpected(fail(ClusterErrorCode::result_overflow,"total hits overflow"));total+=result->total_hits;for(const auto& hit:result->hits)(void)collector.collect({hit.document_id,hit.score});}query::SearchResult merged;merged.total_hits=total;for(auto& hit:collector.results())merged.hits.push_back({std::move(hit.document_id),hit.score});return merged;}
}  // namespace dse::distributed
