#include "dse/distributed/replication.hpp"
#include <algorithm>
#include <set>
#include <utility>
namespace dse::distributed {namespace {
ReplicationError fail(ReplicationErrorCode code,std::string message){return {code,std::move(message)};}
bool same_record(const MutationRecord& a,const MutationRecord& b){return a.shard==b.shard&&a.epoch==b.epoch&&a.operation_id==b.operation_id&&a.sequence==b.sequence&&a.document.id==b.document.id&&a.document.fields==b.document.fields&&a.document.stored_metadata==b.document.stored_metadata&&a.document.version==b.document.version&&a.document.deleted==b.document.deleted;}
bool same_document(const Document& a,const Document& b){return a.id==b.id&&a.fields==b.fields&&a.stored_metadata==b.stored_metadata&&a.version==b.version&&a.deleted==b.deleted;}
}
std::expected<ApplyOutcome,ReplicationError> OrderedReplica::apply(const MutationRecord& record){if(record.shard!=shard_)return std::unexpected(fail(ReplicationErrorCode::wrong_shard,"mutation targets another shard"));if(record.epoch!=epoch_)return std::unexpected(fail(ReplicationErrorCode::wrong_epoch,"mutation epoch does not match replica"));if(record.operation_id.empty())return std::unexpected(fail(ReplicationErrorCode::conflicting_operation,"operation ID is empty"));if(const auto found=operations_.find(record.operation_id);found!=operations_.end()){if(!same_record(found->second,record))return std::unexpected(fail(ReplicationErrorCode::conflicting_operation,"operation ID was reused with different content"));return ApplyOutcome::duplicate;}if(record.sequence<=applied_sequence_)return std::unexpected(fail(ReplicationErrorCode::stale_sequence,"unknown operation has stale sequence"));if(record.sequence!=applied_sequence_+1U)return std::unexpected(fail(ReplicationErrorCode::sequence_gap,"mutation sequence is not contiguous"));auto applied=index_.put(record.document);if(!applied)return std::unexpected(fail(ReplicationErrorCode::mutation_error,applied.error().message));applied_sequence_=record.sequence;operations_.emplace(record.operation_id,record);return ApplyOutcome::applied;}
ReplicaStatus OrderedReplica::status(std::uint64_t primary_sequence)const{return {.node_id=node_,.health=health_,.applied_sequence=applied_sequence_,.lag=primary_sequence>applied_sequence_?primary_sequence-applied_sequence_:0U,.inflight=inflight_};}
std::expected<NodeId,ReplicationError> ReplicaRouter::select(const std::vector<ReplicaStatus>& replicas,std::uint64_t maximum_lag){const ReplicaStatus* best=nullptr;for(const auto& candidate:replicas){if(candidate.health==NodeHealth::unhealthy||candidate.health==NodeHealth::draining||candidate.lag>maximum_lag)continue;if(best==nullptr||candidate.health<best->health||(candidate.health==best->health&&(candidate.lag<best->lag||(candidate.lag==best->lag&&(candidate.inflight<best->inflight||(candidate.inflight==best->inflight&&candidate.node_id<best->node_id))))))best=&candidate;}if(best==nullptr)return std::unexpected(fail(ReplicationErrorCode::no_eligible_replica,"no replica satisfies health and lag policy"));return best->node_id;}
ReplicationGroup::ReplicationGroup(ShardId shard,std::uint64_t epoch,std::vector<NodeId> nodes,std::size_t limit,index::IndexSchema schema):shard_(shard),epoch_(epoch),limit_(limit){replicas_.reserve(nodes.size());for(auto& node:nodes)replicas_.push_back(std::make_unique<OrderedReplica>(std::move(node),shard,epoch,schema));}
std::expected<std::unique_ptr<ReplicationGroup>,ReplicationError> ReplicationGroup::create(ShardId shard,std::uint64_t epoch,std::vector<NodeId> nodes,std::size_t maximum_retained_records,index::IndexSchema schema){std::set<NodeId> unique(nodes.begin(),nodes.end());if(shard.value()==0U||epoch==0U||nodes.empty()||nodes.size()>64U||unique.size()!=nodes.size()||maximum_retained_records==0U)return std::unexpected(fail(ReplicationErrorCode::invalid_topology,"invalid replication group"));return std::unique_ptr<ReplicationGroup>(new ReplicationGroup(shard,epoch,std::move(nodes),maximum_retained_records,std::move(schema)));}
std::expected<MutationReceipt,ReplicationError> ReplicationGroup::submit(std::string operation_id,Document document,AcknowledgementMode mode){std::lock_guard lock(mutex_);const MutationRecord* record_ptr=nullptr;if(const auto found=operation_indices_.find(operation_id);found!=operation_indices_.end()){record_ptr=&log_[found->second];if(!same_document(record_ptr->document,document))return std::unexpected(fail(ReplicationErrorCode::conflicting_operation,"operation ID was reused with different content"));}else{if(log_.size()>=limit_)return std::unexpected(fail(ReplicationErrorCode::log_full,"retained mutation log is full"));MutationRecord record{shard_,epoch_,std::move(operation_id),next_sequence_,std::move(document)};auto primary=replicas_.front()->apply(record);if(!primary)return std::unexpected(primary.error());operation_indices_[record.operation_id]=log_.size();log_.push_back(std::move(record));record_ptr=&log_.back();++next_sequence_;}std::size_t acknowledgements{};for(auto& replica:replicas_){const auto health=replica->status().health;if(replica.get()!=replicas_.front().get()&&(health==NodeHealth::unhealthy||health==NodeHealth::draining))continue;auto applied=replica->apply(*record_ptr);if(applied)++acknowledgements;}if(mode==AcknowledgementMode::all_replicas&&acknowledgements!=replicas_.size())return std::unexpected(fail(ReplicationErrorCode::insufficient_acknowledgements,"mutation committed on primary without every replica acknowledgement"));return MutationReceipt{record_ptr->sequence,acknowledgements};}
std::vector<ReplicaStatus> ReplicationGroup::statuses()const{std::lock_guard lock(mutex_);const auto primary=replicas_.front()->status().applied_sequence;std::vector<ReplicaStatus> result;result.reserve(replicas_.size());for(const auto& replica:replicas_)result.push_back(replica->status(primary));return result;}
std::expected<NodeId,ReplicationError> ReplicationGroup::select_read_replica(std::uint64_t maximum_lag)const{return ReplicaRouter::select(statuses(),maximum_lag);}
std::expected<void,ReplicationError> ReplicationGroup::set_health(const NodeId& node,NodeHealth health){std::lock_guard lock(mutex_);for(auto& replica:replicas_)if(replica->node_id()==node){if(health==NodeHealth::healthy||health==NodeHealth::suspect)for(const auto& record:log_){auto replayed=replica->apply(record);if(!replayed)return std::unexpected(replayed.error());}replica->set_health(health);return{};}return std::unexpected(fail(ReplicationErrorCode::invalid_topology,"node is not in replication group"));}
std::vector<MutationRecord> ReplicationGroup::retained_log()const{std::lock_guard lock(mutex_);return log_;}
}  // namespace dse::distributed
