#include "dse/distributed/shard_rpc.hpp"
#include "dse/query/parser.hpp"
#include <array>
#include <bit>
#include <cerrno>
#include <cstring>
#include <limits>
#include <poll.h>
#include <span>
#include <csignal>
#include <pthread.h>
#include <unistd.h>
#include <vector>
namespace dse::distributed {namespace {
using Bytes=std::vector<std::byte>;RpcError fail(RpcErrorCode code,std::string message){return {code,std::move(message)};}
void u32(Bytes& out,std::uint32_t value){for(unsigned i=0;i<4;++i)out.push_back(static_cast<std::byte>((value>>(8U*i))&0xffU));}void u64(Bytes& out,std::uint64_t value){for(unsigned i=0;i<8;++i)out.push_back(static_cast<std::byte>((value>>(8U*i))&0xffU));}bool text(Bytes& out,std::string_view value){if(value.size()>std::numeric_limits<std::uint32_t>::max())return false;u32(out,static_cast<std::uint32_t>(value.size()));for(char c:value)out.push_back(static_cast<std::byte>(c));return true;}
class Cursor{public:explicit Cursor(std::span<const std::byte> data):data_(data){}std::optional<std::uint8_t> byte(){if(pos_==data_.size())return{};return std::to_integer<std::uint8_t>(data_[pos_++]);}std::optional<std::uint32_t> u32v(){if(data_.size()-pos_<4)return{};std::uint32_t v{};for(unsigned i=0;i<4;++i)v|=static_cast<std::uint32_t>(std::to_integer<std::uint8_t>(data_[pos_++]))<<(8U*i);return v;}std::optional<std::uint64_t> u64v(){if(data_.size()-pos_<8)return{};std::uint64_t v{};for(unsigned i=0;i<8;++i)v|=static_cast<std::uint64_t>(std::to_integer<std::uint8_t>(data_[pos_++]))<<(8U*i);return v;}std::optional<std::string> string(std::uint32_t limit){auto n=u32v();if(!n||*n>limit||*n>data_.size()-pos_)return{};std::string value(reinterpret_cast<const char*>(data_.data()+pos_),*n);pos_+=*n;return value;}bool done()const{return pos_==data_.size();}private:std::span<const std::byte> data_;std::size_t pos_{};};
std::expected<void,RpcError> wait_fd(int fd,short events,std::chrono::steady_clock::time_point deadline){for(;;){const auto now=std::chrono::steady_clock::now();if(now>=deadline)return std::unexpected(fail(RpcErrorCode::timeout,"RPC deadline exceeded"));const auto remaining=std::chrono::duration_cast<std::chrono::milliseconds>(deadline-now);pollfd descriptor{fd,events,0};const int result=::poll(&descriptor,1,static_cast<int>(std::min<std::int64_t>(remaining.count()+1,2147483647)));if(result>0){if((descriptor.revents&(POLLERR|POLLNVAL))!=0)return std::unexpected(fail(RpcErrorCode::io_error,"socket poll error"));if((descriptor.revents&POLLHUP)!=0&&(descriptor.revents&events)==0)return std::unexpected(fail(RpcErrorCode::disconnected,"peer disconnected"));return{};}if(result==0)continue;if(errno!=EINTR)return std::unexpected(fail(RpcErrorCode::io_error,std::strerror(errno)));}}
ssize_t write_without_sigpipe(int fd,const std::byte* data,std::size_t size){sigset_t blocked{};sigset_t previous{};sigemptyset(&blocked);sigaddset(&blocked,SIGPIPE);const int masked=::pthread_sigmask(SIG_BLOCK,&blocked,&previous);if(masked!=0){errno=masked;return -1;}const auto count=::write(fd,data,size);const int saved_errno=errno;if(count<0&&saved_errno==EPIPE&&!sigismember(&previous,SIGPIPE)){timespec zero{};(void)::sigtimedwait(&blocked,nullptr,&zero);}const int restore=::pthread_sigmask(SIG_SETMASK,&previous,nullptr);if(restore!=0&&count>=0){errno=restore;return -1;}errno=saved_errno;return count;}
std::expected<void,RpcError> transfer(int fd,std::span<std::byte> bytes,bool writing,std::chrono::steady_clock::time_point deadline){std::size_t done{};while(done<bytes.size()){auto ready=wait_fd(fd,writing?POLLOUT:POLLIN,deadline);if(!ready)return ready;const auto count=writing ? write_without_sigpipe(fd,bytes.data()+done,bytes.size()-done) : ::read(fd,bytes.data()+done,bytes.size()-done);if(count==0)return std::unexpected(fail(RpcErrorCode::disconnected,"peer disconnected"));if(count<0){if(errno==EINTR||errno==EAGAIN)continue;return std::unexpected(fail(RpcErrorCode::io_error,std::strerror(errno)));}done+=static_cast<std::size_t>(count);}return{};}
std::expected<Bytes,RpcError> receive_frame(int fd,std::chrono::steady_clock::time_point deadline,const RpcLimits& limits){std::array<std::byte,4> header{};auto received=transfer(fd,header,false,deadline);if(!received)return std::unexpected(received.error());Cursor cursor(header);const auto length=cursor.u32v();if(!length||*length>limits.maximum_frame_bytes)return std::unexpected(fail(RpcErrorCode::resource_limit,"RPC frame exceeds limit"));Bytes payload(*length);received=transfer(fd,payload,false,deadline);if(!received)return std::unexpected(received.error());return payload;}
std::expected<void,RpcError> send_frame(int fd,const Bytes& payload,std::chrono::steady_clock::time_point deadline,const RpcLimits& limits){if(payload.size()>limits.maximum_frame_bytes)return std::unexpected(fail(RpcErrorCode::resource_limit,"RPC frame exceeds limit"));Bytes framed;u32(framed,static_cast<std::uint32_t>(payload.size()));framed.insert(framed.end(),payload.begin(),payload.end());return transfer(fd,framed,true,deadline);}
}
std::expected<query::SearchResult,RpcError> ShardRpcClient::search(std::string_view query_text,std::size_t top_k,std::chrono::steady_clock::time_point deadline)const{if(query_text.size()>limits_.maximum_query_bytes||top_k>limits_.maximum_hits)return std::unexpected(fail(RpcErrorCode::resource_limit,"RPC request exceeds limit"));Bytes request;request.push_back(std::byte{1});u64(request,top_k);text(request,query_text);auto sent=send_frame(socket_,request,deadline,limits_);if(!sent)return std::unexpected(sent.error());auto response=receive_frame(socket_,deadline,limits_);if(!response)return std::unexpected(response.error());Cursor cursor(*response);auto version=cursor.byte();auto status=cursor.byte();if(!version||*version!=1U||!status)return std::unexpected(fail(RpcErrorCode::protocol_error,"invalid RPC response"));if(*status!=0U){auto message=cursor.string(limits_.maximum_frame_bytes);return std::unexpected(fail(RpcErrorCode::remote_error,message.value_or("remote search failed")));}auto total=cursor.u64v();auto count=cursor.u32v();if(!total||*total>std::numeric_limits<std::size_t>::max()||!count||*count>limits_.maximum_hits)return std::unexpected(fail(RpcErrorCode::protocol_error,"invalid RPC result header"));query::SearchResult result;result.total_hits=static_cast<std::size_t>(*total);for(std::uint32_t i=0;i<*count;++i){auto id=cursor.string(limits_.maximum_frame_bytes);auto bits=cursor.u64v();if(!id||!bits)return std::unexpected(fail(RpcErrorCode::protocol_error,"invalid RPC hit"));result.hits.push_back({DocumentId(std::move(*id)),std::bit_cast<double>(*bits)});}if(!cursor.done())return std::unexpected(fail(RpcErrorCode::protocol_error,"trailing RPC response bytes"));return result;}
std::expected<void,RpcError> ShardRpcServer::serve_one(int socket,const index::SearchIndexView& index,std::chrono::steady_clock::time_point deadline,RpcLimits limits){auto request=receive_frame(socket,deadline,limits);if(!request)return std::unexpected(request.error());Cursor cursor(*request);auto version=cursor.byte();auto top_k=cursor.u64v();auto query_text=cursor.string(limits.maximum_query_bytes);Bytes response;response.push_back(std::byte{1});if(!version||*version!=1U||!top_k||*top_k>limits.maximum_hits||!query_text||!cursor.done()){response.push_back(std::byte{1});text(response,"invalid search request");return send_frame(socket,response,deadline,limits);}auto parsed=query::parse(*query_text);if(!parsed){response.push_back(std::byte{1});text(response,parsed.error().message);return send_frame(socket,response,deadline,limits);}query::SearchOptions options;options.top_k=static_cast<std::size_t>(*top_k);auto result=query::QueryExecutor(index).search(**parsed,options);if(!result){response.push_back(std::byte{1});text(response,result.error().message);return send_frame(socket,response,deadline,limits);}response.push_back(std::byte{0});u64(response,result->total_hits);u32(response,static_cast<std::uint32_t>(result->hits.size()));for(const auto& hit:result->hits){text(response,hit.document_id.value());u64(response,std::bit_cast<std::uint64_t>(hit.score));}return send_frame(socket,response,deadline,limits);}
}  // namespace dse::distributed
