#include "dse/storage/write_ahead_log.hpp"
#include <array>
#include <bit>
#include <cerrno>
#include <cstring>
#include <fstream>
#include <limits>
#include <span>
#include <system_error>
#include <utility>
#include <fcntl.h>
#include <unistd.h>
namespace dse::storage { namespace {
using Bytes=std::vector<std::byte>; constexpr std::array<std::byte,4> magic{std::byte{'D'},std::byte{'W'},std::byte{'A'},std::byte{'L'}};
WalError fail(WalErrorCode code,std::string message){return {code,std::move(message)};}
void u32(Bytes& out,std::uint32_t value){for(unsigned i=0;i<4;++i)out.push_back(static_cast<std::byte>((value>>(i*8U))&0xffU));}
void u64(Bytes& out,std::uint64_t value){for(unsigned i=0;i<8;++i)out.push_back(static_cast<std::byte>((value>>(i*8U))&0xffU));}
bool add_string(Bytes& out,std::string_view value){if(value.size()>std::numeric_limits<std::uint32_t>::max())return false;u32(out,static_cast<std::uint32_t>(value.size()));for(char c:value)out.push_back(static_cast<std::byte>(c));return true;}
std::uint32_t crc32c(std::span<const std::byte> bytes){std::uint32_t crc=~0U;for(const auto byte:bytes){crc^=std::to_integer<std::uint8_t>(byte);for(int bit=0;bit<8;++bit)crc=(crc>>1U)^(0x82f63b78U&static_cast<std::uint32_t>(-static_cast<std::int32_t>(crc&1U)));}return ~crc;}
class Cursor{public:Cursor(std::span<const std::byte> data,const WalLimits& limits):data_(data),limits_(limits){}std::optional<std::uint8_t> byte(){if(position_==data_.size())return{};return std::to_integer<std::uint8_t>(data_[position_++]);}std::optional<std::uint32_t> u32v(){if(data_.size()-position_<4)return{};std::uint32_t v{};for(unsigned i=0;i<4;++i)v|=static_cast<std::uint32_t>(std::to_integer<std::uint8_t>(data_[position_++]))<<(i*8U);return v;}std::optional<std::uint64_t> u64v(){if(data_.size()-position_<8)return{};std::uint64_t v{};for(unsigned i=0;i<8;++i)v|=static_cast<std::uint64_t>(std::to_integer<std::uint8_t>(data_[position_++]))<<(i*8U);return v;}std::optional<std::string> text(){auto n=u32v();if(!n||*n>limits_.maximum_string_bytes||*n>data_.size()-position_)return{};std::string s(reinterpret_cast<const char*>(data_.data()+position_),*n);position_+=*n;return s;}bool done()const{return position_==data_.size();}private:std::span<const std::byte> data_;const WalLimits& limits_;std::size_t position_{};};
std::expected<Bytes,WalError> encode(const Document& d){Bytes p;if(!add_string(p,d.id.value()))return std::unexpected(fail(WalErrorCode::resource_limit,"document ID is too large"));u64(p,d.version);p.push_back(d.deleted?std::byte{1}:std::byte{0});auto add_map=[&](const auto& values){if(values.size()>std::numeric_limits<std::uint32_t>::max())return false;u32(p,static_cast<std::uint32_t>(values.size()));for(const auto& [k,v]:values)if(!add_string(p,k)||!add_string(p,v))return false;return true;};if(!add_map(d.fields)||!add_map(d.stored_metadata))return std::unexpected(fail(WalErrorCode::resource_limit,"document value is too large"));return p;}
std::expected<Document,WalError> decode(std::span<const std::byte> payload,const WalLimits& limits){Cursor c(payload,limits);auto id=c.text();auto version=c.u64v();auto deleted=c.byte();if(!id||id->empty()||!version||!deleted||*deleted>1U)return std::unexpected(fail(WalErrorCode::corruption,"invalid WAL document header"));Document document{.id=DocumentId(std::move(*id)),.fields={},.stored_metadata={},.version=*version,.deleted=*deleted==1U};auto read_map=[&](auto& target)->bool{auto count=c.u32v();if(!count||*count>1'000'000U)return false;for(std::uint32_t i=0;i<*count;++i){auto key=c.text();auto value=c.text();if(!key||!value||key->empty()||!target.emplace(std::move(*key),std::move(*value)).second)return false;}return true;};if(!read_map(document.fields)||!read_map(document.stored_metadata)||!c.done())return std::unexpected(fail(WalErrorCode::corruption,"invalid WAL document body"));return document;}
std::expected<void,WalError> sync_file(const std::filesystem::path& path){int fd=::open(path.c_str(),O_RDONLY|O_CLOEXEC);if(fd<0)return std::unexpected(fail(WalErrorCode::io_error,std::strerror(errno)));if(::fsync(fd)!=0){const auto message=std::strerror(errno);::close(fd);return std::unexpected(fail(WalErrorCode::io_error,message));}if(::close(fd)!=0)return std::unexpected(fail(WalErrorCode::io_error,std::strerror(errno)));return{};}
} // namespace
std::expected<void,WalError> WriteAheadLog::append(const Document& document)const{auto payload=encode(document);if(!payload)return std::unexpected(payload.error());if(payload->size()>std::numeric_limits<std::uint32_t>::max()||payload->size()>static_cast<std::size_t>(std::numeric_limits<std::streamsize>::max())-12U)return std::unexpected(fail(WalErrorCode::resource_limit,"WAL record is too large"));Bytes record;record.insert(record.end(),magic.begin(),magic.end());u32(record,static_cast<std::uint32_t>(payload->size()));u32(record,crc32c(*payload));record.insert(record.end(),payload->begin(),payload->end());std::ofstream out(path_,std::ios::binary|std::ios::app);if(!out)return std::unexpected(fail(WalErrorCode::io_error,"cannot open WAL"));out.write(reinterpret_cast<const char*>(record.data()),static_cast<std::streamsize>(record.size()));out.flush();if(!out)return std::unexpected(fail(WalErrorCode::io_error,"cannot write WAL"));out.close();return sync_file(path_);}
std::expected<std::vector<Document>,WalError> WriteAheadLog::replay(const WalLimits& limits)const{std::error_code ec;if(!std::filesystem::exists(path_,ec))return std::vector<Document>{};const auto size=std::filesystem::file_size(path_,ec);if(ec)return std::unexpected(fail(WalErrorCode::io_error,ec.message()));if(size>limits.maximum_file_bytes)return std::unexpected(fail(WalErrorCode::resource_limit,"WAL exceeds file limit"));std::ifstream input(path_,std::ios::binary);if(!input)return std::unexpected(fail(WalErrorCode::io_error,"cannot open WAL"));Bytes bytes(static_cast<std::size_t>(size));input.read(reinterpret_cast<char*>(bytes.data()),static_cast<std::streamsize>(bytes.size()));if(!input&&size!=0U)return std::unexpected(fail(WalErrorCode::io_error,"cannot read WAL"));input.close();std::vector<Document> documents;std::size_t position{};std::size_t valid_end{};while(position<bytes.size()){const auto remaining=bytes.size()-position;if(remaining<12U)break;if(!std::equal(magic.begin(),magic.end(),bytes.begin()+static_cast<std::ptrdiff_t>(position)))return std::unexpected(fail(WalErrorCode::corruption,"invalid WAL magic"));position+=4U;auto read32=[&](){std::uint32_t value{};for(unsigned i=0;i<4;++i)value|=static_cast<std::uint32_t>(std::to_integer<std::uint8_t>(bytes[position++]))<<(i*8U);return value;};const auto length=read32();const auto checksum=read32();if(length>limits.maximum_record_bytes)return std::unexpected(fail(WalErrorCode::resource_limit,"WAL record exceeds limit"));if(length>bytes.size()-position)break;if(documents.size()>=limits.maximum_records)return std::unexpected(fail(WalErrorCode::resource_limit,"WAL record count exceeds limit"));const auto payload=std::span<const std::byte>(bytes).subspan(position,length);if(crc32c(payload)!=checksum)return std::unexpected(fail(WalErrorCode::corruption,"WAL checksum mismatch"));auto document=decode(payload,limits);if(!document)return std::unexpected(document.error());documents.push_back(std::move(*document));position+=length;valid_end=position;}if(valid_end<bytes.size()){std::filesystem::resize_file(path_,valid_end,ec);if(ec)return std::unexpected(fail(WalErrorCode::io_error,"cannot truncate torn WAL tail: "+ec.message()));auto synced=sync_file(path_);if(!synced)return std::unexpected(synced.error());}return documents;}
std::expected<void,WalError> WriteAheadLog::reset()const{std::ofstream out(path_,std::ios::binary|std::ios::trunc);if(!out)return std::unexpected(fail(WalErrorCode::io_error,"cannot reset WAL"));out.flush();out.close();return sync_file(path_);}
}  // namespace dse::storage
