#include "dse/distributed/local_cluster.hpp"
#include "dse/query/parser.hpp"
#include <gtest/gtest.h>
#include <array>
#include <cmath>
namespace {
dse::Document document(std::size_t i){const std::array words{"alpha search","beta engine","distributed search","replicated engine"};return {.id=dse::DocumentId("doc-"+std::to_string(i)),.fields={{"body",words[(i+1U)%words.size()]},{"tags",i%2U==0U?"systems":"search"},{"title",words[i%words.size()]}},.stored_metadata={{"timestamp","2026-08-27"}},.version=1};}
TEST(LocalShardCluster, StableRoutingAndParallelResultsMatchSingleIndexOracle){auto cluster=dse::distributed::LocalShardCluster::create(4);ASSERT_TRUE(cluster);for(std::size_t i=0;i<40;++i)ASSERT_TRUE((*cluster)->put(document(i)));EXPECT_EQ((*cluster)->route(dse::DocumentId("stable")),(*cluster)->route(dse::DocumentId("stable")));for(const auto query_text:{"search","title:distributed OR body:engine","search AND NOT beta","tags:systems","timestamp:[2026-01-01 TO *]","*"}){auto query=dse::query::parse(query_text);ASSERT_TRUE(query);for(const auto top_k:{0U,1U,7U,100U}){dse::query::SearchOptions options;options.top_k=top_k;auto distributed=(*cluster)->search(**query,options);ASSERT_TRUE(distributed)<<(distributed?"":distributed.error().message);auto oracle=dse::query::QueryExecutor((*cluster)->oracle_index()).search(**query,options);ASSERT_TRUE(oracle);ASSERT_EQ(distributed->total_hits,oracle->total_hits)<<query_text;ASSERT_EQ(distributed->hits.size(),oracle->hits.size())<<query_text;for(std::size_t i=0;i<oracle->hits.size();++i){EXPECT_EQ(distributed->hits[i].document_id,oracle->hits[i].document_id)<<query_text;EXPECT_NEAR(distributed->hits[i].score,oracle->hits[i].score,1e-12)<<query_text;}}}}
TEST(LocalShardCluster, UpdatesAndDeletesRemainOnOneShard){auto cluster=dse::distributed::LocalShardCluster::create(3);ASSERT_TRUE(cluster);auto first=document(1);const auto shard=(*cluster)->route(first.id);ASSERT_TRUE((*cluster)->put(first));auto updated=document(1);updated.fields["title"]="latest search";updated.version=2;ASSERT_TRUE((*cluster)->put(updated));EXPECT_EQ((*cluster)->route(updated.id),shard);ASSERT_TRUE((*cluster)->erase(updated.id,3));auto query=dse::query::parse("*");ASSERT_TRUE(query);auto result=(*cluster)->search(**query);ASSERT_TRUE(result);EXPECT_EQ(result->total_hits,0U);}
TEST(LocalShardCluster, RejectsEmptyTopology){auto cluster=dse::distributed::LocalShardCluster::create(0);ASSERT_FALSE(cluster);EXPECT_EQ(cluster.error().code,dse::distributed::ClusterErrorCode::invalid_shard_count);}
}  // namespace
