#include "dse/distributed/replication.hpp"
#include <gtest/gtest.h>
#include <atomic>
#include <thread>
#include <vector>
namespace {
dse::Document mutation(std::uint64_t version=1){return {.id=dse::DocumentId("doc"),.fields={{"body","replicated"},{"tags","systems"},{"title","ordered mutation"}},.stored_metadata={{"timestamp","2026-09-06"}},.version=version};}
TEST(OrderedReplica, AppliesContiguousRecordsIdempotently){dse::distributed::OrderedReplica replica(dse::NodeId("node-a"),dse::ShardId(1),7);dse::distributed::MutationRecord record{dse::ShardId(1),7,"op-1",1,mutation()};auto applied=replica.apply(record);ASSERT_TRUE(applied);EXPECT_EQ(*applied,dse::distributed::ApplyOutcome::applied);applied=replica.apply(record);ASSERT_TRUE(applied);EXPECT_EQ(*applied,dse::distributed::ApplyOutcome::duplicate);auto gap=record;gap.operation_id="op-3";gap.sequence=3;EXPECT_EQ(replica.apply(gap).error().code,dse::distributed::ReplicationErrorCode::sequence_gap);auto conflict=record;conflict.document.version=2;EXPECT_EQ(replica.apply(conflict).error().code,dse::distributed::ReplicationErrorCode::conflicting_operation);}
TEST(ReplicationGroup, ExposesAcknowledgementSemanticsAndIdempotentRetry){auto group=dse::distributed::ReplicationGroup::create(dse::ShardId(1),1,{dse::NodeId("primary"),dse::NodeId("replica-a"),dse::NodeId("replica-b")});ASSERT_TRUE(group);auto receipt=(*group)->submit("operation",mutation(),dse::distributed::AcknowledgementMode::all_replicas);ASSERT_TRUE(receipt);EXPECT_EQ(receipt->acknowledgements,3U);auto duplicate=(*group)->submit("operation",mutation(),dse::distributed::AcknowledgementMode::all_replicas);ASSERT_TRUE(duplicate);EXPECT_EQ(duplicate->sequence,receipt->sequence);EXPECT_EQ((*group)->retained_log().size(),1U);ASSERT_TRUE((*group)->set_health(dse::NodeId("replica-b"),dse::distributed::NodeHealth::unhealthy));auto partial=(*group)->submit("next",mutation(2),dse::distributed::AcknowledgementMode::all_replicas);ASSERT_FALSE(partial);EXPECT_EQ(partial.error().code,dse::distributed::ReplicationErrorCode::insufficient_acknowledgements);EXPECT_EQ((*group)->retained_log().size(),2U);ASSERT_TRUE((*group)->set_health(dse::NodeId("replica-b"),dse::distributed::NodeHealth::healthy));auto recovered=(*group)->submit("next",mutation(2),dse::distributed::AcknowledgementMode::all_replicas);ASSERT_TRUE(recovered);EXPECT_EQ(recovered->acknowledgements,3U);}
TEST(ReplicaRouter, PrefersHealthThenLagLoadAndNodeId){std::vector<dse::distributed::ReplicaStatus> replicas{{dse::NodeId("suspect"),dse::distributed::NodeHealth::suspect,9,1,0},{dse::NodeId("busy"),dse::distributed::NodeHealth::healthy,10,0,5},{dse::NodeId("ready"),dse::distributed::NodeHealth::healthy,10,0,1},{dse::NodeId("draining"),dse::distributed::NodeHealth::draining,10,0,0}};auto selected=dse::distributed::ReplicaRouter::select(replicas,2);ASSERT_TRUE(selected);EXPECT_EQ(*selected,dse::NodeId("ready"));replicas[2].health=dse::distributed::NodeHealth::unhealthy;selected=dse::distributed::ReplicaRouter::select(replicas,2);ASSERT_TRUE(selected);EXPECT_EQ(*selected,dse::NodeId("busy"));replicas[1].health=dse::distributed::NodeHealth::unhealthy;selected=dse::distributed::ReplicaRouter::select(replicas,0);ASSERT_FALSE(selected);EXPECT_EQ(selected.error().code,dse::distributed::ReplicationErrorCode::no_eligible_replica);}
TEST(ReplicationGroup, SerializesConcurrentMutationProducers){auto group=dse::distributed::ReplicationGroup::create(dse::ShardId(2),1,{dse::NodeId("primary"),dse::NodeId("replica")});ASSERT_TRUE(group);std::atomic_bool failed{};std::vector<std::thread> producers;for(int thread=0;thread<4;++thread)producers.emplace_back([&,thread]{for(int i=0;i<10;++i){auto doc=mutation();doc.id=dse::DocumentId("doc-"+std::to_string(thread)+"-"+std::to_string(i));auto result=(*group)->submit("op-"+std::to_string(thread)+"-"+std::to_string(i),std::move(doc),dse::distributed::AcknowledgementMode::all_replicas);if(!result)failed=true;}});for(auto& producer:producers)producer.join();EXPECT_FALSE(failed.load());const auto log=(*group)->retained_log();ASSERT_EQ(log.size(),40U);for(std::size_t i=0;i<log.size();++i)EXPECT_EQ(log[i].sequence,i+1U);}
}  // namespace
