#include "dse/storage/index_writer.hpp"
#include "dse/storage/write_ahead_log.hpp"
#include <gtest/gtest.h>
#include <atomic>
#include <filesystem>
#include <fstream>
namespace {
class WalDir{public:WalDir(){static std::atomic_uint64_t n{};path_=std::filesystem::temp_directory_path()/("dse-wal-"+std::to_string(++n));std::filesystem::create_directories(path_);}~WalDir(){std::error_code ignored;std::filesystem::remove_all(path_,ignored);}const auto& path()const{return path_;}private:std::filesystem::path path_;};
dse::Document make_document(std::string id,std::uint64_t version){return {.id=dse::DocumentId(std::move(id)),.fields={{"body","durable body"},{"tags","wal"},{"title","recovered"}},.stored_metadata={{"timestamp","2026-08-27"}},.version=version};}
TEST(WriteAheadLog, RoundTripsRecordsAndRepairsTruncatedTail){WalDir dir;dse::storage::WriteAheadLog wal(dir.path()/"wal");ASSERT_TRUE(wal.append(make_document("a",1)));ASSERT_TRUE(wal.append(make_document("b",2)));auto replay=wal.replay();ASSERT_TRUE(replay);ASSERT_EQ(replay->size(),2U);EXPECT_EQ((*replay)[1].id,dse::DocumentId("b"));const auto valid_size=std::filesystem::file_size(wal.path());{std::ofstream tail(wal.path(),std::ios::binary|std::ios::app);tail.write("DWA",3);}replay=wal.replay();ASSERT_TRUE(replay);EXPECT_EQ(replay->size(),2U);EXPECT_EQ(std::filesystem::file_size(wal.path()),valid_size);ASSERT_TRUE(wal.append(make_document("c",3)));replay=wal.replay();ASSERT_TRUE(replay);ASSERT_EQ(replay->size(),3U);EXPECT_EQ(replay->back().id,dse::DocumentId("c"));}
TEST(WriteAheadLog, RejectsChecksumDamageAndResourceLimits){WalDir dir;dse::storage::WriteAheadLog wal(dir.path()/"wal");ASSERT_TRUE(wal.append(make_document("a",1)));{std::fstream file(wal.path(),std::ios::binary|std::ios::in|std::ios::out);file.seekg(15);char value{};file.get(value);file.seekp(15);file.put(static_cast<char>(value^0x40));}auto replay=wal.replay();ASSERT_FALSE(replay);EXPECT_EQ(replay.error().code,dse::storage::WalErrorCode::corruption);replay=wal.replay({.maximum_file_bytes=1});ASSERT_FALSE(replay);EXPECT_EQ(replay.error().code,dse::storage::WalErrorCode::resource_limit);}
TEST(WriteAheadLog, WriterRecoversUnflushedMutationAndCheckpointsAfterRefresh){WalDir dir;dse::storage::WriteAheadLog wal(dir.path()/"WRITE-AHEAD.log");ASSERT_TRUE(wal.append(make_document("crash-survivor",7)));auto writer=dse::storage::IndexWriter::open(dir.path());ASSERT_TRUE(writer)<<(writer?"":writer.error().message);EXPECT_EQ((*writer)->statistics().buffered_mutations,1U);ASSERT_TRUE((*writer)->refresh());auto view=(*writer)->open_search_view();ASSERT_TRUE(view);ASSERT_NE(view->document(dse::DocumentId("crash-survivor")),nullptr);EXPECT_EQ(view->document(dse::DocumentId("crash-survivor"))->document.version,7U);EXPECT_EQ(std::filesystem::file_size(wal.path()),0U);}
}  // namespace
